name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Base plugin
          base: header
          # Isometric calndar plugin
          plugin_isocalendar: yes
          # Languages plugin
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 2%
          plugin_languages_details: percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_load: 500
          plugin_languages_aliases: "JavaScript:JS, TypeScript:TS"
          plugin_languages_ignored: html, css, less, dockerfile, makefile, shell
          # RSS plugin
          plugin_rss: yes
          plugin_rss_source: https://slawinski.dev/rss.xml
          plugin_rss_limit: 4
          # Display order
          config_order: base.header, isocalendar, languages
